CREATE TABLE APARTS(
    PID INTEGER PRIMARY KEY,
    ADDRESS CHAR(100) NOT NULL,
    PRICE_LOW INT,
    PRICE_HIGH INT,
    BED_LOW INT,
    BED_HIGH INT,
    Dog_Friendly INTEGER NOT NULL,
    Cat_Friendly INTEGER NOT NULL,
    In_Unit_Washer_Dryer INTEGER NOT NULL,
    Dishwasher INTEGER NOT NULL,
    Parking INTEGER NOT NULL,
    Fitness_Center INTEGER NOT NULL,
    CITY CHAR(30),
    AID INTEGER NOT NULL,
    FOREIGN KEY (AID) REFERENCES AGENTS(AID)
);

-- Multiple apartments <-> One agent
CREATE TABLE AGENTS(
    AID INTEGER PRIMARY KEY,
    AGENT CHAR(50) UNIQUE
);

-- Statistics for each city
CREATE TABLE STATS(
    SID INTEGER PRIMARY KEY,
    CITY CHAR(30),
    BED_ONE INT NOT NULL,
    BED_TWO INT NOT NULL,
    BED_THREE INT NOT NULL
);